# fly.toml app configuration file generated for games-long-pond-9933 on 2024-09-22T20:22:57+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'games-long-pond-9933'
primary_region = 'cdg'

[build]
  builder = 'dockerfile'


[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
